/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Pojos.Allergen;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import static Interface.Intro.loadAllAllergens;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio Antelo
 */
public class Allergens extends javax.swing.JFrame {

    /**
     * Creates new form Allergens
     */
    
    String userName;
    
    public Allergens(String userName) {
        initComponents();
        this.userName = userName;
        this.setSize(new Dimension(450,500));        
        setIcon();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        construction_check = new javax.swing.JCheckBox();
        gluten_check = new javax.swing.JCheckBox();
        lactose_check = new javax.swing.JCheckBox();
        nuts_check = new javax.swing.JCheckBox();
        eggs_check = new javax.swing.JCheckBox();
        seafood_check = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("LRG Intellectual property. All Rights Reserved");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 500));
        setMinimumSize(new java.awt.Dimension(450, 500));
        setPreferredSize(new java.awt.Dimension(450, 500));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Allergens");

        construction_check.setBackground(new java.awt.Color(153, 255, 153));
        construction_check.setText("Others ...");
        construction_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                construction_checkActionPerformed(evt);
            }
        });

        gluten_check.setBackground(new java.awt.Color(153, 255, 153));
        gluten_check.setText("Gluten");

        lactose_check.setBackground(new java.awt.Color(153, 255, 153));
        lactose_check.setText("Lactose");
        lactose_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lactose_checkActionPerformed(evt);
            }
        });

        nuts_check.setBackground(new java.awt.Color(153, 255, 153));
        nuts_check.setText("Nuts");
        nuts_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuts_checkActionPerformed(evt);
            }
        });

        eggs_check.setBackground(new java.awt.Color(153, 255, 153));
        eggs_check.setText("Eggs");
        eggs_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggs_checkActionPerformed(evt);
            }
        });

        seafood_check.setBackground(new java.awt.Color(153, 255, 153));
        seafood_check.setText("Seafood");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lactose_75.png"))); // NOI18N

        submit_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("LRG Intellectual property. All Rights Reserved");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gluten_75.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/nuts_75.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eggs_75.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/other_75.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/seafood_75.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("LRG Intellectual property. All Rights Reserved");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(seafood_check)
                            .addComponent(gluten_check)
                            .addComponent(nuts_check)
                            .addComponent(jLabel5))
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eggs_check)
                            .addComponent(jLabel6)
                            .addComponent(lactose_check)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(construction_check, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(659, 659, 659)
                    .addComponent(jLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lactose_check)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eggs_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(construction_check))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gluten_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuts_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seafood_check)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(submit_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(451, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(36, 36, 36)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        boolean gluten = gluten_check.isSelected();
        boolean lactose = lactose_check.isSelected();
        boolean nuts = nuts_check.isSelected();
        boolean eggs = eggs_check.isSelected();
        boolean seafood = seafood_check.isSelected();
        Allergen allergen = new Allergen(this.userName,gluten,lactose,nuts,eggs,seafood);
        saveAllergenInfo("UserAllergens.txt","data",allergen);
        Clips clipsFrame = new Clips(allergen);
        clipsFrame.setLocationRelativeTo(null);
        clipsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void eggs_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggs_checkActionPerformed

    }//GEN-LAST:event_eggs_checkActionPerformed

    private void construction_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_construction_checkActionPerformed
        construction_check.setSelected(false);
        JOptionPane.showMessageDialog(new JFrame(), "... Section in construction ...", "Please wait",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_construction_checkActionPerformed

    private void nuts_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuts_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuts_checkActionPerformed

    private void lactose_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lactose_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lactose_checkActionPerformed

    
    public static void saveAllergenInfo(String nombreArchivo,String directorio, Allergen allergen)
    {
        
        FileOutputStream fileOutputStream=null;
        ObjectOutputStream objectOutputStream=null;
        
        ArrayList<Allergen> userAllergens = loadAllAllergens(nombreArchivo,directorio);

        File fichero = new File(directorio,nombreArchivo);
        
            try{
            
                fileOutputStream = new FileOutputStream(fichero);
                objectOutputStream = new ObjectOutputStream(fileOutputStream);
                userAllergens.add(allergen);
                Iterator<Allergen> it = userAllergens.iterator();
                objectOutputStream.writeObject(userAllergens.size());
                while(it.hasNext())
                {
                    Allergen al = (Allergen)it.next();

                    objectOutputStream.writeObject(al);
                }
    
            }catch(IOException ex)
            {
            } finally {
                    try {
                        if (fileOutputStream != null) {
                            fileOutputStream.close();
                        }
                    } catch (IOException ex) {
                        ex.printStackTrace();
                        }
                    try {
                        if (objectOutputStream != null) {
                            objectOutputStream.close();
                        }
                   } catch (IOException ex) {
                       ex.printStackTrace();
                }
            }
        
    }
    
        private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/logo_mni.jpg")));
        this.setTitle("LRG");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox construction_check;
    private javax.swing.JCheckBox eggs_check;
    private javax.swing.JCheckBox gluten_check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox lactose_check;
    private javax.swing.JCheckBox nuts_check;
    private javax.swing.JCheckBox seafood_check;
    private javax.swing.JButton submit_button;
    // End of variables declaration//GEN-END:variables
}
