/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Pojos.User;
import static Interface.Intro.*;
import static Pojos.Validator.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Sergio Antelo
 */
public class UserInfo extends javax.swing.JFrame {

    /**
     * Creates new form UserInfo
     */
    
    String userName;
    
    public UserInfo() {
        initComponents();
         
        //Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setSize(new Dimension(450,500));
        setIcon();   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        name_surname_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        age_textfield = new javax.swing.JTextField();
        username_textfield = new javax.swing.JTextField();
        password_textfield = new javax.swing.JTextField();
        signup_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        try{
            Image img = ImageIO.read(getClass().getResource("back.png"));
            jButton1.setIcon(new ImageIcon(img));
        }catch(Exception ex){
            System.out.println(ex);
        }
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        name_surname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_surname_textfieldActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Name and Surname");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Age");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Username");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("LRG Intellectual property. All Rights Reserved");

        signup_button.setText("Sign up");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("Hello!!");

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Insert the following information:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7))
                                            .addGap(2, 2, 2)))
                                    .addComponent(jLabel4))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(age_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_surname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(signup_button))
                    .addComponent(jButton1))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_surname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(age_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(signup_button)
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void name_surname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_surname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_surname_textfieldActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        String name = name_surname_textfield.getText();
        String ageSt = age_textfield.getText();
        userName = username_textfield.getText();
        String password = password_textfield.getText();

        boolean valStringb = valString(name);
        boolean valAgeLimitsb = valAgeLimits(18,99,ageSt);
        boolean checkUserNameb = checkUserName(userName);
        if((valStringb)&&(valAgeLimitsb)&&(!checkUserNameb))
        {
            int age = Integer.parseInt(ageSt);
            String encodedPassword = encodePassword(password);
            User user1 = new User(name,age,userName,encodedPassword);
            saveUserInfo("UserPasswords.txt","data",user1);
            this.setVisible(false);
            Allergens allergensFrame = new Allergens(user1.getUserName());
            allergensFrame.setLocationRelativeTo(null); 
            allergensFrame.setVisible(true); 
            this.dispose();
            
        }
        panel2Icons(valStringb,valAgeLimitsb,checkUserNameb);
        
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Intro intro = new Intro();
        
        
        intro.setLocationRelativeTo(null); 
        intro.setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed
       
  
    public void panel2Icons(boolean valStringb, boolean valAgeLimitsb, boolean checkUserNameb)
    {

       if(!valStringb)
           {
               name_surname_textfield.setBorder(new LineBorder(Color.red,2));
               JOptionPane.showMessageDialog(new JFrame(), "Check your values, something is incorrect!", "Error",JOptionPane.ERROR_MESSAGE);
           }else
           {
               name_surname_textfield.setBorder(new LineBorder(Color.black,1));
           }
           if(!valAgeLimitsb)
           {
               age_textfield.setBorder(new LineBorder(Color.red,2));
               JOptionPane.showMessageDialog(new JFrame(), "Check your values, something is incorrect!", "Error",JOptionPane.ERROR_MESSAGE);
           }else
           {
               age_textfield.setBorder(new LineBorder(Color.black,1));
           }
           if(checkUserNameb)
           {
               username_textfield.setBorder(new LineBorder(Color.red,2));
               JOptionPane.showMessageDialog(new JFrame(), "Check your values, something is incorrect!", "Error",JOptionPane.ERROR_MESSAGE);
           }else
           {
               username_textfield.setBorder(new LineBorder(Color.black,1));
           }
    }
    
    public static boolean checkUserName(String us)
    {
        boolean ans = false;
        User user = null;
        
        ArrayList<User> namePasswords = loadAllUsers("UserPasswords.txt","data");
       
        Iterator it = namePasswords.iterator();
        for(int i = 0; i<namePasswords.size();i++)
        {
            user = (User)it.next();
            if(user.getUserName().equals(us))
            {
                ans = true;
                break;
            }
        }
        
        return ans;
    }
         
    public static void saveUserInfo(String nombreArchivo,String directorio, User user)
    {
        
        FileOutputStream fileOutputStream=null;
        ObjectOutputStream objectOutputStream=null;
        
        ArrayList<User> users = loadAllUsers(nombreArchivo,directorio);
        
        
        
        File fichero = new File(directorio,nombreArchivo);
        
            try{
            
                fileOutputStream = new FileOutputStream(fichero);
                objectOutputStream = new ObjectOutputStream(fileOutputStream);
                users.add(user);
                Iterator<User> it = users.iterator();
                objectOutputStream.writeObject(users.size());
                while(it.hasNext())
                {
                    User us = (User)it.next();

                    objectOutputStream.writeObject(us);
                }
    
            }catch(IOException ex)
            {
            } finally {
                    try {
                        if (fileOutputStream != null) {
                            fileOutputStream.close();
                        }
                    } catch (IOException ex) {
                        ex.printStackTrace();
                        }
                    try {
                        if (objectOutputStream != null) {
                            objectOutputStream.close();
                        }
                   } catch (IOException ex) {
                       ex.printStackTrace();
                }
            }
        
    }
    
        private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/logo_mni.jpg")));
        this.setTitle("LRG");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_textfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name_surname_textfield;
    private javax.swing.JTextField password_textfield;
    private javax.swing.JButton signup_button;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
